INSERT INTO almacen.producto (cod_producto, name) VALUES 
('P0', 'PlayStation 5'), 
('P1', 'PlayStation 4'), 
('P2', 'Xbox Series X'), 
('P3', 'Xbox Series S'), 
('P4', 'Nintendo Switch OLED'), 
('P5', 'Nintendo Switch'), 
('P6', 'Nintendo Switch Lite'), 
('P7', 'PlayStation 3'), 
('P8', 'Xbox One'), 
('P9', 'Xbox 360'), 
('P10', 'Nintendo 3DS'), 
('P11', 'Nintendo 2DS'), 
('P12', 'PlayStation Vita'), 
('P13', 'PSP (PlayStation Portable)'), 
('P14', 'Sega Genesis Mini'), 
('P15', 'SNES Classic'), 
('P16', 'NES Classic'), 
('P17', 'Atari Flashback'), 
('P18', 'PlayStation Classic'), 
('P19', 'Nintendo GameCube'), 
('P20', 'Nintendo Wii'), 
('P21', 'Nintendo Wii U'), 
('P22', 'Xbox'), 
('P23', 'Sega Dreamcast'), 
('P24', 'Sega Saturn'), 
('P25', 'The Last of Us Part II'), 
('P26', 'God of War'), 
('P27', 'Spider-Man: Miles Morales'), 
('P28', 'Ghost of Tsushima'), 
('P29', 'Ratchet & Clank: Rift Apart'), 
('P30', 'Uncharted 4: A Thiefs End'), 
('P31', 'Horizon Forbidden West'), 
('P32', 'Gran Turismo 7'), 
('P33', 'Bloodborne'), 
('P34', 'Days Gone'), 
('P35', 'Final Fantasy VII Remake'), 
('P36', 'Demons Souls (PS5)'), 
('P37', 'Resident Evil Village'), 
('P38', 'Elden Ring'), 
('P39', 'Death Stranding'), 
('P40', 'Returnal'), 
('P41', 'Sackboy: A Big Adventure'), 
('P42', 'Mortal Kombat 11'), 
('P43', 'FIFA 23'), 
('P44', 'NBA 2K23'), 
('P45', 'Halo Infinite'), 
('P46', 'Forza Horizon 5'), 
('P47', 'Gears 5'), 
('P48', 'Sea of Thieves'), 
('P49', 'Fable'), 
('P50', 'Forza Motorsport 7'), 
('P51', 'Microsoft Flight Simulator'), 
('P52', 'State of Decay 2'), 
('P53', 'Ori and the Will of the Wisps'), 
('P54', 'Quantum Break'), 
('P55', 'Sunset Overdrive'), 
('P56', 'The Outer Worlds'), 
('P57', 'Psychonauts 2'), 
('P58', 'Cyberpunk 2077'), 
('P59', 'Assassins Creed Valhalla'), 
('P60', 'Red Dead Redemption 2'), 
('P61', 'Call of Duty: Modern Warfare II'), 
('P62', 'Doom Eternal'), 
('P63', 'Fallout 76'), 
('P64', 'The Elder Scrolls V: Skyrim'), 
('P65', 'The Legend of Zelda: Breath of the Wild'), 
('P66', 'Super Mario Odyssey'), 
('P67', 'Animal Crossing: New Horizons'), 
('P68', 'Mario Kart 8 Deluxe'), 
('P69', 'Splatoon 3'), 
('P70', 'Pokémon Sword and Shield'), 
('P71', 'Super Smash Bros. Ultimate'), 
('P72', 'Xenoblade Chronicles 3'), 
('P73', 'Metroid Dread'), 
('P74', 'Luigis Mansion 3'), 
('P75', 'Fire Emblem: Three Houses'), 
('P76', 'Kirby and the Forgotten Land'), 
('P77', 'Donkey Kong Country: Tropical Freeze'), 
('P78', 'Bayonetta 3'), 
('P79', 'Mario Party Superstars'), 
('P80', 'Octopath Traveler'), 
('P81', 'Astral Chain'), 
('P82', 'Hades'), 
('P83', 'Splatoon 2'), 
('P84', 'Minecraft'), 
('P85', 'Grand Theft Auto V'), 
('P86', 'The Witcher 3: Wild Hunt'), 
('P87', 'Dark Souls III'), 
('P88', 'Sekiro: Shadows Die Twice'), 
('P89', 'Overwatch'), 
('P90', 'Fortnite'), 
('P91', 'Apex Legends'), 
('P92', 'Among Us'), 
('P93', 'Battlefield 2042'), 
('P94', 'Call of Duty: Warzone'), 
('P95', 'Rocket League'), 
('P96', 'Destiny 2'), 
('P97', 'League of Legends'), 
('P98', 'Dota 2'), 
('P99', 'Counter-Strike: Global Offensive'), 
('P100', 'DualSense Wireless Controller (PS5)'), 
('P101', 'Xbox Wireless Controller'), 
('P102', 'Nintendo Switch Pro Controller'), 
('P103', 'Joy-Con Controllers (Nintendo Switch)'), 
('P104', 'PlayStation VR2'), 
('P105', 'Xbox Elite Wireless Controller Series 2'), 
('P106', 'Nintendo Switch Dock Set'), 
('P107', 'PlayStation Camera (PS4)'), 
('P108', 'Xbox Series X Expansion Card'), 
('P109', 'Razer Kishi (Control para móviles)'), 
('P110', 'Oculus Quest 2'), 
('P111', 'Gaming Headset (PS5, Xbox, Switch)'), 
('P112', 'PlayStation Plus Subscription'), 
('P113', 'Xbox Game Pass Subscription'), 
('P114', 'Nintendo Switch Online Subscription'), 
('P115', 'Amiibo Figures'), 
('P116', 'PlayStation Move Controllers'), 
('P117', 'Gaming Keyboard'), 
('P118', 'Gaming Mouse'), 
('P119', 'VR Headset for PC'), 
('P120', 'Mario + Rabbids Kingdom Battle'), 
('P121', 'New Pokémon Snap'), 
('P122', 'Monster Hunter Rise'), 
('P123', 'Super Mario 3D World + Bowsers Fury'), 
('P124', 'The Legend of Zelda'), 
('P125', 'Links Awakening'), 
('P126', 'Paper Mario: The Origami King'), 
('P127', 'Captain Toad: Treasure Tracker'), 
('P128', 'Tetris 99'), 
('P129', 'Ring Fit Adventure'), 
('P130', 'Uncharted'), 
('P131', 'The Nathan Drake Collection'), 
('P132', 'Persona 5 Royal'), 
('P133', 'Final Fantasy XVI'), 
('P134', 'Ghostwire: Tokyo'), 
('P135', 'Kena: Bridge of Spirits'), 
('P136', 'The Last Guardian'), 
('P137', 'Nioh 2'), 
('P138', 'Infamous: Second Son'), 
('P139', 'Until Dawn'), 
('P140', 'Ratchet & Clank (PS4)'), 
('P141', 'Hellblade: Senuas Sacrifice'), 
('P142', 'Crackdown 3'), 
('P143', 'ReCore'), 
('P144', 'Ryse: Son of Rome'), 
('P145', 'Dead Rising 4'), 
('P146', 'Gears of War: Ultimate Edition'), 
('P147', 'Halo: The Master Chief Collection'), 
('P148', 'Rare Replay'), 
('P149', 'Killer Instinct'), 
('P150', 'Titanfall 2'), 
('P151', 'Super Nintendo Entertainment System (SNES)'), 
('P152', 'Nintendo Entertainment System (NES)'), 
('P153', 'Sega Genesis'), 
('P154', 'PlayStation 1'), 
('P155', 'Game Boy Color'), 
('P156', 'Game Boy Advance'), 
('P157', 'Atari 2600'), 
('P158', 'Neo Geo'), 
('P159', 'Sega Master System'), 
('P160', 'TurboGrafx-16'), 
('P161', 'StarCraft II'), 
('P162', 'Diablo III'), 
('P163', 'World of Warcraft'), 
('P164', 'Half-Life 2'), 
('P165', 'Civilization VI'), 
('P166', 'The Sims 4'), 
('P167', 'Baldurs Gate 3'), 
('P168', 'Valheim'), 
('P169', 'Rust'), 
('P170', 'Age of Empires IV'), 
('P171', 'Resident Evil 4'), 
('P172', 'Metal Gear Solid V'), 
('P173', 'The Phantom Pain'), 
('P174', 'Just Dance 2023'), 
('P175', 'NBA 2K24'), 
('P176', 'FIFA 24'), 
('P177', 'Madden NFL 24'), 
('P178', 'Monster Hunter World'), 
('P179', 'Borderlands 3'), 
('P180', 'Far Cry 6'), 
('P181', 'Assassins Creed Mirage'), 
('P182', 'Gaming Chair'), 
('P183', 'PlayStation 5 Charging Station'), 
('P184', 'Xbox Rechargeable Battery'), 
('P185', 'Nintendo Switch Carrying Case'), 
('P186', 'RGB Gaming Mouse Pad'), 
('P187', 'PS5 Media Remote'), 
('P188', 'Xbox Play and Charge Kit'), 
('P189', 'External Hard Drive for Consoles'), 
('P190', 'Nintendo Switch GameCube'), 
('P191', 'Controller Adapter'), 
('P192', 'Racing Wheel for Consoles'), 
('P193', 'Game Boy'), 
('P194', 'PSP Go'), 
('P195', 'Neo Geo Pocket Color'), 
('P196', 'Atari Lynx'), 
('P197', 'Sega Game Gear'), 
('P198', 'PS Vita Slim'), 
('P199', 'Nintendo DS Lite');
SELECT COUNT(*) FROM almacen.producto;